/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        canvas: 'rgb(var(--canvas) / <alpha-value>)',
        elevated: 'rgb(var(--elevated) / <alpha-value>)',
        sunken: 'rgb(var(--sunken) / <alpha-value>)',
        ink: 'rgb(var(--ink) / <alpha-value>)',
        'ink-2': 'rgb(var(--ink-2) / <alpha-value>)',
        'ink-3': 'rgb(var(--ink-3) / <alpha-value>)',
        heat: 'rgb(var(--heat) / <alpha-value>)',
        'heat-hover': 'rgb(var(--heat-hover) / <alpha-value>)',
        success: 'rgb(var(--success) / <alpha-value>)',
        warning: 'rgb(var(--warning) / <alpha-value>)',
        error: 'rgb(var(--error) / <alpha-value>)',
        scrim: 'var(--scrim)',
        line: 'var(--line)',
        'line-strong': 'var(--line-strong)',
        'heat-dim': 'var(--heat-dim)',
        gold: 'rgb(var(--gold) / <alpha-value>)',
        'gold-ink': 'rgb(var(--gold-ink) / <alpha-value>)',
        'gold-line': 'var(--gold-line)',
        'gold-dim': 'var(--gold-dim)',
        glass: 'var(--glass)',
        'glass-strong': 'var(--glass-strong)',
        'glass-line': 'var(--glass-line)',
        'aurora-1': 'rgb(var(--aurora-1) / <alpha-value>)',
        'aurora-2': 'rgb(var(--aurora-2) / <alpha-value>)',
        'aurora-3': 'rgb(var(--aurora-3) / <alpha-value>)',
        'aurora-4': 'rgb(var(--aurora-4) / <alpha-value>)',
        'aurora-5': 'rgb(var(--aurora-5) / <alpha-value>)',
      },
      borderRadius: {
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        lg: 'var(--radius-lg)',
        xl: 'var(--radius-xl)',
      },
      fontFamily: {
        display: ['Fraunces', 'Playfair Display', 'Iowan Old Style', 'Palatino Linotype', 'Georgia', 'serif'],
        sans: ['Inter', 'ui-sans-serif', 'system-ui', '-apple-system', 'Segoe UI', 'sans-serif'],
        mono: ['JetBrains Mono', 'ui-monospace', 'SF Mono', 'Menlo', 'monospace'],
      },
      boxShadow: {
        overlay: 'var(--shadow-overlay)',
        soft: 'var(--shadow-soft)',
      },
      transitionTimingFunction: {
        'out-expo': 'cubic-bezier(0.16, 1, 0.3, 1)',
        spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
    },
  },
  plugins: [],
}
